# Generated by Django 3.2.4 on 2021-08-26 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorys are: Birth, Death, or Name', models.TextField(default='Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.TextField(default='Search')),
            ],
        ),
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('status', models.CharField(default='', max_length=2)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('birth', models.DateField(verbose_name='birth Y-m-d')),
                ('death', models.DateField(verbose_name='death Y-m-d')),
                ('image', models.ImageField(upload_to='')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('credit', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seacrh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default='There is nothing listed for this saint.'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='entry',
            name='saint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='saints_website.saint'),
            preserve_default=False,
        ),
    ]
