# Generated by Django 3.2.4 on 2021-08-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0003_auto_20210826_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.AddField(
            model_name='seacrh',
            name='Categorys are: Birth, Death, or Name',
            field=models.TextField(default='Birth'),
        ),
        migrations.AddField(
            model_name='seacrh',
            name='search',
            field=models.TextField(default='Search'),
        ),
    ]
