# Generated by Django 3.2.4 on 2021-08-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0004_auto_20210826_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seacrh',
            options={'verbose_name_plural': 'Searches'},
        ),
        migrations.RemoveField(
            model_name='seacrh',
            name='Categorys are: Birth, Death, or Name',
        ),
        migrations.AddField(
            model_name='seacrh',
            name='category',
            field=models.TextField(default='Birth, Death, or Name'),
        ),
    ]
