# Generated by Django 3.2.4 on 2021-09-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0005_auto_20210826_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('prayer', models.ImageField(upload_to='')),
                ('caption', models.CharField(blank=True, max_length=50)),
                ('atl', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Seacrh',
        ),
        migrations.AddField(
            model_name='saint',
            name='alt',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
