# Generated by Django 3.2.4 on 2021-11-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0007_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='saint',
            name='cal_Image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
