# Generated by Django 3.2.4 on 2021-11-05 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0008_auto_20211104_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='month',
            field=models.CharField(default=datetime.datetime(2021, 11, 5, 22, 3, 3, 72998), max_length=50),
        ),
    ]
