# Generated by Django 3.2.4 on 2021-11-06 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0009_calendar_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.CharField(default=datetime.datetime(2021, 11, 6, 12, 17, 10, 917775), max_length=50),
        ),
    ]
