# Generated by Django 3.2.4 on 2021-11-06 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0010_alter_calendar_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='saint',
            name='m_feast',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.CharField(default=datetime.datetime(2021, 11, 6, 12, 35, 6, 93722), max_length=50),
        ),
    ]
