# Generated by Django 3.2.4 on 2021-11-06 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0011_auto_20211106_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='saint',
            name='d_feast',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.CharField(default=datetime.datetime(2021, 11, 6, 12, 45, 20, 601218), max_length=50),
        ),
    ]
