# Generated by Django 3.2.4 on 2022-05-13 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0012_auto_20211106_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='saint',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.CharField(default=datetime.datetime(2022, 5, 13, 15, 11, 16, 474341), max_length=50),
        ),
        migrations.AlterField(
            model_name='saint',
            name='status',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
