# Generated by Django 3.2.4 on 2022-05-17 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0013_auto_20220513_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.CharField(default=datetime.datetime(2022, 5, 17, 13, 48, 20, 870378), max_length=50),
        ),
        migrations.AlterField(
            model_name='saint',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
