# Generated by Django 3.2.4 on 2022-05-17 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0014_auto_20220517_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.CharField(default=datetime.datetime(2022, 5, 17, 13, 59, 20, 571636), max_length=50),
        ),
    ]
