# Generated by Django 3.2.4 on 2022-05-19 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints_website', '0021_alter_calendar_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saint',
            name='summary',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.CharField(default=datetime.datetime(2022, 5, 19, 14, 51, 30, 11697), max_length=50),
        ),
    ]
